### ISSUE TITLE
Cards are not added to non-existent deck in the 1st sync

### ISSUE THREAD

**Issue by bolauce** [ShootingKing-AM/Obsidian_to_Anki#9] opened 2023-03-03 02:10 UTC
After replacing the files (main, manifest.json, README.md and styles) in the obsidian-to-anki folder with those from your .zip, I still have an issue when it comes to creating the cards.

The TARGET DECK goes through (e.g., if I haven't made a folder in Anki but specify it in Obsidian, it will create the folder), but the cards that I try to create do not.

Thoughts?

**Comment by ShootingKing-AM** [comment] 2023-03-03 11:09
Sorry for no instructions on how to install. You need to [download](https://github.com/ShootingKing-AM/Obsidian_to_Anki/releases/download/3.4.2/Obsidian_to_Anki-3.4.2.zip) the `.zip` file in releases (https://github.com/ShootingKing-AM/Obsidian_to_Anki/releases/tag/3.4.2) and extract it to your `.obsidian/plugins` folder in your vault's root. 

This will overwrite existing old plugin files. Then do restart your obsidian.

**Comment by rmcguire4** [comment] 2023-03-06 15:38
Hello! I'm having the same problem as @bolauce. New decks are created if they're not already in Anki, but none of my new cards are going in.

I downloaded the zip and extracted to .obsidians/plugins, overwrote, and restarted, as you mentioned above.

I don't receive any errors, just messages.* I filtered all the messages down to the files that I was expecting to go to Anki.

![image](https://user-images.githubusercontent.com/108299278/223155781-8f34e1d5-2e2a-47f9-a966-e990829b5673.png)

On the left side, in Anki, you'll see decks for Russian and Modern Standard Arabic have been created in Anki, but they're empty (the Obsidian files for the notes in these are new and the ones I was trying to sync). The corresponding Obsidian files in the console are at the top of that list on the right. It appears to "look" at them, but doesn't do anything further.

I searched for one of the files that was "looked" at to see if there were any other messages associated with it and found none:
![image](https://user-images.githubusercontent.com/108299278/223156294-b41573de-3054-466a-9a7e-b8636feabba5.png)

Please let me know if I can provide any other screenshots that might help. I appreciate you making a fix for this. It's one of my most used plugins!


_*Sadly, all the other messages are because of a typo in my template for my note type ( I have lots of editing to do.)_

**Comment by ShootingKing-AM** [comment] 2023-03-06 15:48
Oh! Can you share your Obsidian Note ? Which has cards written ? 

Is the Russian Deck created by plugin or by you through Anki ?

If you didn't create it, Can you Delete the deck and create the deck manually via anki and sync again.

If Plugin created it, After 1st Sync is done, Can you Edit the Note (BOCEMB (similar looking idk russian)). Write something in the note and re-Sync and see what happens ?

**Comment by rmcguire4** [comment] 2023-03-06 16:03
Sure!

Do you want the whole thing, or just where the card is? Here is the card part:
![image](https://user-images.githubusercontent.com/108299278/223160982-d76d5cab-57a5-46cc-ae0c-0d62fed756f0.png)

The Russian deck in my original screenshot was created by the plugin.

I deleted the plugin-created Russian deck and made one manually in Anki. I got the same results. Here is a screenshot of that:
![image](https://user-images.githubusercontent.com/108299278/223162437-4bc8db05-6dca-4bf6-9f24-59e3d570918c.png)

Changing the note after the first sync doesn't change anything: 
![image](https://user-images.githubusercontent.com/108299278/223162811-f128e844-ced9-45aa-b113-e504e99a204a.png)

"FL to Eng (And Reversed)" is one of my custom card types that was working previously. I changed our sample to the "Basic" default card type and also got the same results: 
![image](https://user-images.githubusercontent.com/108299278/223163526-b7d8d593-adbc-4abe-acdc-d9f1d765fc91.png)


Thanks!

**Comment by ShootingKing-AM** [comment] 2023-03-06 16:20
I don't see any START or END tags, The plugin will not think its a note.

https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Note-formatting

**Comment by rmcguire4** [comment] 2023-03-06 17:05
Oops! I must have accidentally deleted it while testing things earlier. This time, no Russian notes transferred. But! Without my mess up, I did get an error:

 "plugin:obsidian-to-anki-plugin:53168 Failed to add note  {deckName: 'Russian', modelName: 'FL Basic (and reversed card)', fields: {…}, options: {…}, tags: Array(6)}  in file Languages/Vocabulary/Russian/восемь.md  due to error  deck was not found: Russian"

![image](https://user-images.githubusercontent.com/108299278/223176352-bbebc407-c7d3-43fb-9f3d-86d19eace650.png)

I had deleted the Russian deck in Anki before this attempt. Despite saying one wasn't found, the Russian deck was created by the plugin after this same attempt.

Interestingly, a different note that was sent to a target deck that already existed, DID go through.
![image](https://user-images.githubusercontent.com/108299278/223177041-32f12a55-2391-4db6-8d9a-93312f7f3b54.png)

Because of the one that went through, I left the Russian deck that was created by the plugin from this try in Anki, cleared the file and media caches in Obsidian, and hit the button to send to Anki again. This time, cards went through:
![image](https://user-images.githubusercontent.com/108299278/223178378-079b5c2c-bdd4-4dec-9766-2b59c7010ede.png)

Cards are also created when the deck is created manually in Anki before running the plugin in Obsidian.

**Comment by ShootingKing-AM** [comment] 2023-03-06 21:11
Yes, Deck was not found hence created. But is there any Issue now ?

**Comment by rmcguire4** [comment] 2023-03-06 21:14
Yes, there's still an issue. It's still creating a deck but not putting cards in that if that deck doesn't already exist.

**Comment by ShootingKing-AM** [comment] 2023-03-06 21:16
> If Plugin created it, After 1st Sync is done, Can you Edit the Note (BOCEMB (similar looking file.md)). Write something in the note and re-Sync and see what happens ?

Did you try this (https://github.com/ShootingKing-AM/Obsidian_to_Anki/issues/9#issuecomment-1456384292) ?

**Comment by rmcguire4** [comment] 2023-03-06 21:26
Yes. The edited note goes in as long as the deck already exists in Anki.

**Comment by ShootingKing-AM** [comment] 2023-03-06 21:40
I see, so the issue is only in the first sync of new deck. From second sync of the new deck post editing it works normal.

**Comment by rmcguire4** [comment] 2023-03-07 14:22
That's correct. Sorry for the delay.

**Comment by ShootingKing-AM** [comment] 2023-03-07 19:20
Its okay, thanks for the confirmation : )

**Closed** 2023-03-12 12:58 UTC
Labels: bug, documentation

**Comment by ShootingKing-AM** [comment] 2023-03-12 13:02
This is fixed in v3.4.3 (https://github.com/ShootingKing-AM/Obsidian_to_Anki/releases/tag/3.4.3). You can try it, if its still not fixed feel free to reopen the issue

**Comment by rmcguire4** [comment] 2023-03-13 15:58
Perfect! It worked. You rock!
